import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, mkdir, writeFile, cp } from "node:fs/promises";
import os from "node:os"; import path from "node:path";
import { validateRepository } from "../scripts/validate-content.mjs";

const source = (id="source-one", jurisdiction="AU") => ({schemaVersion:1,id,type:"guideline",title:"Exact source",authorsOrOrganisation:["Organisation"],publication:null,publishedAt:"2026-01-01",updatedAt:null,doi:null,url:"https://example.test/exact",accessedAt:"2026-07-15",jurisdiction,language:"en-AU",peerReviewed:false,retractedOrCorrected:false,notes:"Fixture source."});
const moduleRecord = () => ({schemaVersion:1,id:"fixture",slug:"fixture",title:"Fixture",description:"Fixture module.",category:"symptom",status:"draft",audience:"Adults",jurisdictions:["AU"],locale:"en-AU",summary:"Summary.",safety:{emergencySummary:"Emergency summary.",redFlags:[{text:"Seek help.",action:"urgent_assessment",sourceIds:["source-one"]}],vulnerableGroups:[]},claims:[{id:"fixture-claim",statement:"A material claim.",outcome:"pain",population:"adults",intervention:{name:"care",formulation:null,regimenStudied:null},comparison:null,evidence:{certainty:"low",direction:"benefit",effectSummary:null,rationale:"Limited evidence."},sourceIds:["source-one"],caveats:[],jurisdictions:["AU"],reviewedAt:null}],practicalGuidance:[],myths:[],jurisdictionNotes:[],relatedModules:[],sourceIds:["source-one"],review:{researchOwner:"Researcher",evidenceReviewer:null,clinicalReviewer:null,editorialReviewer:null,lastEvidenceSearch:"2026-07-15",lastClinicallyReviewed:null,nextReviewDue:null,changeSummary:"Draft."}});
async function fixture(mods=[moduleRecord()], sources=[source()]) { const root=await mkdtemp(path.join(os.tmpdir(),"coldflu-")); for(const d of ["schemas","content/modules","content/sources","content/research"]) await mkdir(path.join(root,d),{recursive:true}); await cp("schemas/module.schema.json",path.join(root,"schemas/module.schema.json")); await cp("schemas/source.schema.json",path.join(root,"schemas/source.schema.json")); for(let i=0;i<mods.length;i++){await writeFile(path.join(root,"content/modules",`${i}.json`),JSON.stringify(mods[i])); const rd=path.join(root,"content/research",mods[i].slug); await mkdir(rd,{recursive:true}); for(const n of ["protocol.md","search-log.md","screening.md","excluded-studies.md"])await writeFile(path.join(rd,n),"fixture"); for(const n of ["extraction.json","claim-source-map.json"])await writeFile(path.join(rd,n),"{}");} for(let i=0;i<sources.length;i++)await writeFile(path.join(root,"content/sources",`${i}.json`),JSON.stringify(sources[i])); return root; }
const messages = r => r.errors.map(e=>e.message).join(" | ");
test("accepts a valid canonical draft",async()=>assert.equal((await validateRepository(await fixture())).errors.length,0));
test("rejects invalid schema",async()=>{const m=moduleRecord();delete m.title;assert.match(messages(await validateRepository(await fixture([m]))),/required property 'title'/)});
test("rejects duplicate module ids and slugs",async()=>assert.match(messages(await validateRepository(await fixture([moduleRecord(),moduleRecord()]))),/duplicate module id.*duplicate module slug/));
test("rejects duplicate source ids",async()=>assert.match(messages(await validateRepository(await fixture([moduleRecord()],[source(),source()]))),/duplicate source id/));
test("rejects missing source references",async()=>{const m=moduleRecord();m.claims[0].sourceIds=["missing"];assert.match(messages(await validateRepository(await fixture([m]))),/references missing source/)});
test("rejects missing related modules for published content",async()=>{const m=published();m.relatedModules=["absent"];assert.match(messages(await validateRepository(await fixture([m]))),/missing related module/)});
function published(){const m=moduleRecord();m.status="published";m.claims[0].reviewedAt="2026-06-30";Object.assign(m.review,{evidenceReviewer:"Evidence Reviewer",clinicalReviewer:"Clinical Reviewer",editorialReviewer:"Editor",lastClinicallyReviewed:"2026-07-01",nextReviewDue:"2027-01-01"});return m;}
test("rejects published content missing reviewers and dates",async()=>{const m=moduleRecord();m.status="published";assert.match(messages(await validateRepository(await fixture([m]))),/evidenceReviewer.*lastClinicallyReviewed/)});
test("rejects overdue published modules",async()=>{const m=published();m.review.nextReviewDue="2026-01-01";assert.match(messages(await validateRepository(await fixture([m]),"2026-07-15")),/overdue/)});
test("rejects placeholders in published modules",async()=>{const m=published();m.summary="TODO";assert.match(messages(await validateRepository(await fixture([m]))),/placeholder/)});
test("rejects unsupported jurisdictions",async()=>{const m=moduleRecord();m.jurisdictions=["ZZ"];assert.match(messages(await validateRepository(await fixture([m]))),/unsupported jurisdiction/)});
test("rejects emergency content without local source",async()=>{const m=published();assert.match(messages(await validateRepository(await fixture([m],[source("source-one","GB")]))),/supporting Australian source/)});
test("rejects missing research artefacts",async()=>{const root=await fixture();await import("node:fs/promises").then(fs=>fs.rm(path.join(root,"content/research/fixture/screening.md")));assert.match(messages(await validateRepository(root)),/research package missing screening/)});
test("rejects malformed research JSON",async()=>{const root=await fixture();await writeFile(path.join(root,"content/research/fixture/extraction.json"),"{");assert.match(messages(await validateRepository(root)),/malformed extraction/)});
test("rejects claim review dates without an accountable reviewer",async()=>{const m=moduleRecord();m.claims[0].reviewedAt="2026-07-01";m.review.evidenceReviewer="Codex AI";assert.match(messages(await validateRepository(await fixture([m]))),/without an accountable evidence reviewer/)});
test("requires reviewedAt for every published claim",async()=>{const m=published();m.claims[0].reviewedAt=null;assert.match(messages(await validateRepository(await fixture([m]))),/requires reviewedAt/)});
test("rejects claim review dates after clinical review",async()=>{const m=published();m.claims[0].reviewedAt="2026-07-02";assert.match(messages(await validateRepository(await fixture([m]))),/after the module clinical review date/)});
