export type PrivateMediaRecord={id:string;title:string;mediaType:"video"|"podcast";creator:string;publisher:string;officialMediaUrl:string;publisherPageUrl:string|null;platform:"publisher-site"|"youtube"|"apple-podcasts"|"spotify"|"other";publishedAt:string|null;durationSeconds:number|null;jurisdiction:"AU"|"NZ"|"GB"|"US"|"GLOBAL"|"OTHER";language:string;primaryModuleSlug:string;relatedModuleSlugs:string[];categories:string[];topics:string[];speakerNames:string[];speakerCredentials:string[];description:string;whyIncluded:string;importantCaveats:string[];transcriptUrl:string|null;transcriptStatus:"publisher-transcript"|"human-transcript"|"automatic-transcript"|"not-available"|"not-verified";captionsStatus:"human-captions"|"automatic-captions"|"not-available"|"not-applicable"|"not-verified";linkStatus:"verified"|"needs-recheck"|"broken";lastLinkCheckedAt:string;editorialStatus:"curated"|"candidate"|"needs-recheck"|"outdated";claimVerificationStatus:"supplementary-not-claim-verified"};
type Seed={s:string;t:"video"|"podcast";title:string;p:string;url:string;j:"AU"|"NZ"|"GB"|"US"|"GLOBAL"|"OTHER";related?:string[];status?:"curated"|"candidate"|"needs-recheck";date?:string;duration?:number;transcript?:boolean};
const seeds:Seed[]=[
{s:"cough",t:"video",title:"Mayo Clinic Minute - Managing respiratory illness at home",p:"Mayo Clinic",url:"https://www.youtube.com/watch?v=zldc_C2a-vI",j:"US"},
{s:"runny-or-blocked-nose",t:"video",title:"Mayo Clinic Minute: Is It a Cold or Allergies?",p:"Mayo Clinic",url:"https://newsnetwork.mayoclinic.org/?p=89952",j:"US"},
{s:"fever",t:"video",title:"Febrile convulsions: learn what to watch out for and how to act in an emergency",p:"Royal Children's Hospital Melbourne",url:"https://www.youtube.com/watch?v=7sbwGb-XPYs",j:"AU"},
{s:"sinus-pressure-and-headache",t:"video",title:"Mayo Clinic Minute - Help for a sinus infection",p:"Mayo Clinic",url:"https://www.youtube.com/watch?v=LsUbAc1NmPE",j:"US"},
{s:"loss-of-taste-or-smell",t:"video",title:"The Importance of Smell and Taste",p:"Johns Hopkins Medicine",url:"https://www.youtube.com/watch?v=s3jffujJsnE",j:"US"},
{s:"ear-pressure-or-blockage",t:"video",title:"Eustachian Tube Dysfunction",p:"Johns Hopkins Medicine",url:"https://www.youtube.com/watch?v=aEjnt1Y5yq4",j:"US"},
{s:"hydration",t:"video",title:"Dehydration in children",p:"Sydney Children's Hospitals Network",url:"https://www.youtube.com/watch?v=6aseDnjIL-o",j:"AU"},
{s:"gargles-saline-sprays-and-nasal-irrigation",t:"video",title:"How To Use a Neti Pot",p:"Cleveland Clinic",url:"https://www.youtube.com/watch?v=7MEOELgeaO4",j:"US"},
{s:"otc-medicines-by-active-ingredient",t:"video",title:"Flu: Medicine Safety and Children",p:"Centers for Disease Control and Prevention",url:"https://www.youtube.com/watch?v=uqFXces_Usk",j:"US"},
{s:"babies-and-young-children",t:"video",title:"WHO's Science in 5 - Respiratory diseases in children",p:"World Health Organization",url:"https://www.youtube.com/watch?v=Sg5BsVsnTpk",j:"GLOBAL"},
{s:"asthma-copd-and-chronic-respiratory-conditions",t:"video",title:"Triggers - Cold and flu",p:"Asthma Australia",url:"https://www.youtube.com/watch?v=7eubowBTPYY",j:"AU"},
{s:"cardiovascular-disease-and-high-blood-pressure",t:"video",title:"Blood Pressure Facts: Cold & Flu Medicine",p:"American Heart Association",url:"https://www.youtube.com/watch?v=2uk1NVGmVEo",j:"US"},
{s:"household-precautions",t:"video",title:"Ventilation to reduce the spread of respiratory infections",p:"Somerset Council",url:"https://www.youtube.com/watch?v=KzOyFHF-Hz4",j:"GB"},
{s:"influenza-vaccination",t:"video",title:"Top 3 questions - Flu vaccination, what is in it and how safe it is",p:"Australian Government Department of Health",url:"https://www.health.gov.au/resources/videos/top-3-questions-flu-vaccination-what-is-in-it-and-how-safe-it-is?language=en",j:"AU",transcript:true},
{s:"sore-throat",t:"podcast",title:"Therapeutic Guidelines Sore Throat",p:"Australian Prescriber",url:"https://australianprescriber.tg.org.au/podcast/episode-138-therapeutic-guidelines-sore-throat.html",j:"AU",transcript:true},
{s:"fatigue-and-body-aches",t:"podcast",title:"The coronavirus long-haulers - what do we know?",p:"ABC",url:"https://www.abc.net.au/listen/programs/healthreport/the-coronavirus-long-haulers-long-term-effects-coronavirus/12710520",j:"AU",transcript:true},
{s:"humidity-and-steam",t:"podcast",title:"Heated, humidified air for the common cold",p:"Cochrane",url:"https://www.cochrane.org/podcasts/10.1002/14651858.CD001728.pub6",j:"GLOBAL",status:"needs-recheck"},
{s:"rest-sleep-and-positioning",t:"podcast",title:"Clocks and Cycles: Episode I",p:"Yale School of Medicine",url:"https://medicine.yale.edu/media-player/yjbm-podcast-clocks-and-cycles-episode-i/",j:"US",transcript:true},
{s:"nutrition-during-illness",t:"podcast",title:"How can you boost your immune system?",p:"ABC",url:"https://www.abc.net.au/listen/programs/whats-that-rash/boost-immune-system-cold-flu/103708480",j:"AU",transcript:true},
{s:"complementary-and-traditional-remedies",t:"podcast",title:"Zinc for the prevention and treatment of the common cold",p:"Cochrane",url:"https://www.cochrane.org/podcasts/10.1002/14651858.CD014914.pub2",j:"GLOBAL",transcript:true},
{s:"lozenges-and-throat-sprays",t:"podcast",title:"Choosing a nonsteroidal anti-inflammatory drug for pain",p:"Australian Prescriber",url:"https://australianprescriber.tg.org.au/podcast/episode-198-choosing-a-nonsteroidal-anti-inflammatory-drug-for-pain.html",j:"AU",status:"candidate"},
{s:"warm-compresses",t:"podcast",title:"Managing and Treating Sinus Infections with Dr. Mohamad Chaaban",p:"Cleveland Clinic",url:"https://my.clevelandclinic.org/podcasts/health-essentials/managing-and-treating-sinus-infections-with-dr-mohamad-chaaban",j:"US"},
{s:"prescription-antivirals-and-timing",t:"podcast",title:"First flu for two years: cases on the rise",p:"RNZ",url:"https://www.rnz.co.nz/national/programmes/ninetonoon/audio/2018843037/first-flu-for-two-years-cases-on-the-rise",j:"NZ"},
{s:"pregnancy-and-breastfeeding",t:"podcast",title:"Drug safety in pregnancy",p:"Australian Prescriber",url:"https://australianprescriber.tg.org.au/podcast/episode-183-drug-safety-in-pregnancy.html",j:"AU",transcript:true},
{s:"older-and-immunocompromised-people",t:"podcast",title:"What we know about long COVID",p:"RACP Pomegranate Health",url:"https://www.racp.edu.au/podcast/detail/View/ep89-what-we-know-about-long-covid",j:"AU",transcript:true},
{s:"sleep-activity-stress-and-general-health",t:"podcast",title:"Is it OK to exercise when you're sick?",p:"ABC",url:"https://www.abc.net.au/listen/programs/whats-that-rash/sick-cold-flu-exercise/105644748",j:"AU",transcript:true},
{s:"when-to-seek-care",t:"podcast",title:"Bronchiectasis in children",p:"Goodfellow Unit",url:"https://www.goodfellowunit.org/podcast/bronchiectasis-children",j:"NZ",status:"candidate"},
{s:"cold-flu-covid-strep-allergies",t:"podcast",title:"Loss of Smell and Covid",p:"Johns Hopkins Medicine",url:"https://podcasts.hopkinsmedicine.org/loss-of-smell-and-covid/",j:"US",transcript:true}
];
export const privateMediaLibrary:PrivateMediaRecord[]=seeds.map((x,i)=>({id:`media-${String(i+1).padStart(2,"0")}-${x.s}`,title:x.title,mediaType:x.t,creator:x.p,publisher:x.p,officialMediaUrl:x.url,publisherPageUrl:x.url,platform:x.url.includes("youtube.com")?"youtube":"publisher-site",publishedAt:x.date??null,durationSeconds:x.duration??null,jurisdiction:x.j,language:"en",primaryModuleSlug:x.s,relatedModuleSlugs:x.related??[],categories:[],topics:[x.s],speakerNames:[],speakerCredentials:["not verified"],description:`Supplementary ${x.t} selected for orientation to ${x.s.replaceAll("-"," ")}.`,whyIncluded:"Provides a credible starting point for reviewer orientation and further source checking.",importantCaveats:[x.status==="candidate"?"Topic fit is indirect; retained as a visible candidate coverage gap pending a better dedicated item.":"Inclusion does not verify spoken claims or replace Australian guidance."],transcriptUrl:x.transcript?x.url:null,transcriptStatus:x.transcript?"publisher-transcript":"not-verified",captionsStatus:x.t==="video"?"not-verified":"not-applicable",linkStatus:x.status==="needs-recheck"?"needs-recheck":"verified",lastLinkCheckedAt:"2026-07-15",editorialStatus:x.status??"curated",claimVerificationStatus:"supplementary-not-claim-verified"}));
