import {getResearchAssignments,type ResearchAssignment} from "./assignments";import {artefactProgress} from "./progress";
export type QuestStatus="available"|"completed"|"blocked"|"requires human reviewer";
export interface ResearchQuest{id:string;title:string;module:string;reason:string;criteria:string;evidence:string;effort:"quick"|"focused"|"substantial";href:string;status:QuestStatus;manualOnly:boolean}
export async function getResearchQuests():Promise<ResearchQuest[]>{const assignments=await getResearchAssignments(),quests:ResearchQuest[]=[];for(const a of assignments){if(["researching","canonical-draft","evidence-review"].includes(a.status)){const pack=await artefactProgress(a.slug);for(const file of pack.missing.slice(0,2))quests.push({id:`${a.slug}-${file}`,title:`Complete ${file}`,module:a.module,reason:"The tracked research package is missing a required artefact.",criteria:`${file} exists in content/research/${a.slug}/ and passes validation.`,evidence:`Missing file: content/research/${a.slug}/${file}`,effort:file.endsWith(".json")?"focused":"quick",href:`/research-preview/canonical/${a.slug}`,status:"available",manualOnly:false})}if(a.status==="assigned")quests.push({id:`${a.slug}-return`,title:"Prepare or receive the assigned research bundle",module:a.module,reason:"The assignment has not yet produced an intake-ready return.",criteria:"A provenance-preserving return exists at the path recorded in docs/ASSIGNMENTS.md.",evidence:`Assignment status is ${a.status}.`,effort:"substantial",href:"/research-preview/governance",status:a.researcher.includes("Codex")?"available":"blocked",manualOnly:false});if(a.evidenceReview!=="complete"&&["researching","canonical-draft","evidence-review"].includes(a.status))quests.push(reviewQuest(a,"evidence"));if(a.clinicalReview!=="complete"&&["evidence-review","clinical-review"].includes(a.status))quests.push(reviewQuest(a,"clinical"));}return quests}
function reviewQuest(a:ResearchAssignment,kind:"evidence"|"clinical"):ResearchQuest{return {id:`${a.slug}-${kind}-review`,title:`Arrange independent ${kind} review`,module:a.module,reason:`An accountable ${kind} reviewer is required; workspace actions cannot complete this gate.`,criteria:`A named accountable reviewer completes the governed ${kind} review record.`,evidence:`docs/ASSIGNMENTS.md records ${kind} review as not complete.`,effort:"substantial",href:"/research-preview/governance",status:"requires human reviewer",manualOnly:true}}
export const badgeCriteria=[
 {id:"citation-cartographer",title:"Citation Cartographer",criteria:"A canonical module has a present claim-source-map.json artefact."},
 {id:"bias-checker",title:"Bias Checker",criteria:"A canonical module has present risk-of-bias.md notes."},
 {id:"gap-finder",title:"Gap Finder",criteria:"A canonical module has a present evidence-gaps.md record."},
 {id:"research-pack-ready",title:"Research Pack Ready",criteria:"All 11 required research artefacts are present for a module."},
 {id:"independent-review-ready",title:"Independent Review Ready",criteria:"evidence-review-readiness.md is present; this does not mean review is complete."},
] as const;
